### ISSUE TITLE
Searching crashes with "Uncaught (in promise) RuntimeError: unreachable" error

### ISSUE THREAD

**Issue by lurifaxel** [bbawj/obsidian-semantic-search#2] opened 2023-05-08 19:28 UTC
Hi,

I'm trying out the extension but searching my vault doesn't work. I've successfully generated embeddings and inputs, so my API key and network connection work.

If some system settings are helpful: I'm on a MacBook Pro (M1 chip), MacOS 13.3.1, Obsidian Version 1.2.7 

It looks like this with the dev tools enabled in Obsidian:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/12863511/236914051-c497a2c2-fed5-4cc8-af28-1a3448a393ad.png">

Stack trace in dev tools in Obsidian.
```
Uncaught (in promise) RuntimeError: unreachable
    at 00c97b3e:0xe453c
    at 00c97b3e:0xe933a
    at 00c97b3e:0xf00ee
    at 00c97b3e:0xf2957
    at 00c97b3e:0xf09b6
    at 00c97b3e:0xa3c58
    at 00c97b3e:0x9a147
    at 00c97b3e:0x239da
    at 00c97b3e:0xe467b
    at 00c97b3e:0xc9efc
$func1008	@	00c97b3e:0xe453c
$func1117	@	00c97b3e:0xe933a
$func1370	@	00c97b3e:0xf00ee
$func1512	@	00c97b3e:0xf2957
$func1396	@	00c97b3e:0xf09b6
$func364	@	00c97b3e:0xa3c58
$func321	@	00c97b3e:0x9a147
$func103	@	00c97b3e:0x239da
$func1010	@	00c97b3e:0xe467b
$func642	@	00c97b3e:0xc9efc
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab	@	00c97b3e:0xf48a5
__wbg_adapter_30	@	plugin:bbawj-semantic-search:251
real	@	plugin:bbawj-semantic-search:238
Promise.then (async)		
imports.wbg.__wbg_then_ec5db6d509eb475f	@	plugin:bbawj-semantic-search:830
$func1799	@	00c97b3e:0xf51ca
$func932	@	00c97b3e:0xe044d
$func987	@	00c97b3e:0xe330a
$func780	@	00c97b3e:0xd6274
$func1404	@	00c97b3e:0xf0c12
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab	@	00c97b3e:0xf48a5
__wbg_adapter_30	@	plugin:bbawj-semantic-search:251
real	@	plugin:bbawj-semantic-search:238
Promise.then (async)		
imports.wbg.__wbg_then_f753623316e2873a	@	plugin:bbawj-semantic-search:834
$func463	@	00c97b3e:0xb461b
$func658	@	00c97b3e:0xcb95a
$func103	@	00c97b3e:0x220db
$func1010	@	00c97b3e:0xe467b
$func642	@	00c97b3e:0xc9efc
$_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab	@	00c97b3e:0xf48a5
__wbg_adapter_30	@	plugin:bbawj-semantic-search:251
real	@	plugin:bbawj-semantic-search:238
Promise.then (async)		
imports.wbg.__wbg_then_ec5db6d509eb475f	@	plugin:bbawj-semantic-search:830
$func1799	@	00c97b3e:0xf51ca
$func928	@	00c97b3e:0xe00b6
$func1245	@	00c97b3e:0xed314
$func1050	@	00c97b3e:0xe65b0
$wasm_bindgen__convert__closures__invoke2_mut__h044aa7c8580432a2	@	00c97b3e:0xf4735
__wbg_adapter_184	@	plugin:bbawj-semantic-search:307
cb0	@	plugin:bbawj-semantic-search:814
imports.wbg.__wbg_new_9d3a9ce4282a18a8	@	plugin:bbawj-semantic-search:819
$func1930	@	00c97b3e:0xf5885
$get_suggestions	@	00c97b3e:0xecdd2
get_suggestions	@	plugin:bbawj-semantic-search:277
getSuggestions	@	plugin:bbawj-semantic-search:1142
button.onclick
```

**Comment by bbawj** [comment] 2023-05-08 20:11
Hi, are you on the latest version of the plugin?

**Comment by lurifaxel** [comment] 2023-05-09 06:57
Not sure if it's the latest, but it's version 0.1.4. I don't see any way to trigger an update manually in Obsidian, at least!

**Comment by bbawj** [comment] 2023-05-09 09:42
Yes that is the latest! If you don't mind, maybe you could upload your embedding.csv file for me to try the search on my machine.

**Comment by lurifaxel** [comment] 2023-05-09 18:50
Ah, I now realize the embeddings never worked! Generating input worked, I can see input.csv in my vault. But creating the embeddings result in an error. I suppose that explains why the query doesn't work!

This is the request payload:

<img width="332" alt="image" src="https://github.com/bbawj/obsidian-semantic-search/assets/12863511/ed67f38a-5c34-4064-b266-8ff9fe4ee8c6">

Response:
<img width="392" alt="image" src="https://github.com/bbawj/obsidian-semantic-search/assets/12863511/e263561a-f471-4b1e-8144-d3487887c599">

Stack trace: 
```
plugin:bbawj-semantic-search:571          POST https://api.openai.com/v1/embeddings 400


imports.wbg.__wbg_fetch_56a6919da5e4c21c | @ | plugin:bbawj-semantic-search:571
-- | -- | --
  | $func1026 | @ | 00c97b3e:0xe5338
  | $func123 | @ | 00c97b3e:0x3e058
  | $func104 | @ | 00c97b3e:0x246cc
  | $func1010 | @ | 00c97b3e:0xe467b
  | $func642 | @ | 00c97b3e:0xc9efc
  | $_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab | @ | 00c97b3e:0xf48a5
  | __wbg_adapter_30 | @ | plugin:bbawj-semantic-search:251
  | real | @ | plugin:bbawj-semantic-search:238
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_ec5db6d509eb475f | @ | plugin:bbawj-semantic-search:830
  | $func1799 | @ | 00c97b3e:0xf51ca
  | $func932 | @ | 00c97b3e:0xe044d
  | $func987 | @ | 00c97b3e:0xe330a
  | $func780 | @ | 00c97b3e:0xd6274
  | $func1403 | @ | 00c97b3e:0xf0bc3
  | $_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab | @ | 00c97b3e:0xf48a5
  | __wbg_adapter_30 | @ | plugin:bbawj-semantic-search:251
  | real | @ | plugin:bbawj-semantic-search:238
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_f753623316e2873a | @ | plugin:bbawj-semantic-search:834
  | $func463 | @ | 00c97b3e:0xb461b
  | $func658 | @ | 00c97b3e:0xcb95a
  | $func104 | @ | 00c97b3e:0x23ed2
  | $func1010 | @ | 00c97b3e:0xe467b
  | $func642 | @ | 00c97b3e:0xc9efc
  | $_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab | @ | 00c97b3e:0xf48a5
  | __wbg_adapter_30 | @ | plugin:bbawj-semantic-search:251
  | real | @ | plugin:bbawj-semantic-search:238
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_ec5db6d509eb475f | @ | plugin:bbawj-semantic-search:830
  | $func1799 | @ | 00c97b3e:0xf51ca
  | $func932 | @ | 00c97b3e:0xe044d
  | $func987 | @ | 00c97b3e:0xe330a
  | $func780 | @ | 00c97b3e:0xd6274
  | $func1403 | @ | 00c97b3e:0xf0bc3
  | $_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab | @ | 00c97b3e:0xf48a5
  | __wbg_adapter_30 | @ | plugin:bbawj-semantic-search:251
  | real | @ | plugin:bbawj-semantic-search:238
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_f753623316e2873a | @ | plugin:bbawj-semantic-search:834
  | $func463 | @ | 00c97b3e:0xb461b
  | $func753 | @ | 00c97b3e:0xd3fcf
  | $func104 | @ | 00c97b3e:0x23e20
  | $func1010 | @ | 00c97b3e:0xe467b
  | $func642 | @ | 00c97b3e:0xc9efc
  | $_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h18b6f7bb621664ab | @ | 00c97b3e:0xf48a5
  | __wbg_adapter_30 | @ | plugin:bbawj-semantic-search:251
  | real | @ | plugin:bbawj-semantic-search:238
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_ec5db6d509eb475f | @ | plugin:bbawj-semantic-search:830
  | $func1799 | @ | 00c97b3e:0xf51ca
  | $func928 | @ | 00c97b3e:0xe00b6
  | $func1245 | @ | 00c97b3e:0xed314
  | $func1037 | @ | 00c97b3e:0xe5b57
  | $wasm_bindgen__convert__closures__invoke2_mut__h044aa7c8580432a2 | @ | 00c97b3e:0xf4735
  | __wbg_adapter_184 | @ | plugin:bbawj-semantic-search:307
  | cb0 | @ | plugin:bbawj-semantic-search:814
  | imports.wbg.__wbg_new_9d3a9ce4282a18a8 | @ | plugin:bbawj-semantic-search:819
  | $func1930 | @ | 00c97b3e:0xf5885
  | $generateembeddingscommand_get_embeddings | @ | 00c97b3e:0xef2bd
  | get_embeddings | @ | plugin:bbawj-semantic-search:340
  | confirm_button.onclick
```

**Comment by junwuzhang19** [comment] 2023-05-31 20:02
> Thanks for discovering this issue!
> 
> I think that the issue may be prevalent in large vaults with alot of data, due to my misunderstanding of the OpenAI embedding endpoint maximum tokens limit.
> 
> I am adding a new setting to add batching into the generate embedding process which should hopefully workaround this, by allowing the user to break up large token requests.
> 
> Edit: could you try release 0.2.0 and increase the batch number to see if this problem still persists?

I faced the same problem. My vault contains 200+ notes, 20k words and 20 attachments. I set the batch to the largest 100, but the error still exists.

**Comment by bbawj** [comment] 2023-05-31 21:32
Hi @junwuzhang19 @lurifaxel, there was a bug in the implementation for batching. Could you try the [new release v0.2.2](https://github.com/bbawj/obsidian-semantic-search/releases/tag/0.2.2) to see if you still encounter the same error?

**Comment by simonSlamka** [comment] 2023-06-13 00:22
+1

> Hi @junwuzhang19 @lurifaxel, there was a bug in the implementation for batching. Could you try the [new release v0.2.2](https://github.com/bbawj/obsidian-semantic-search/releases/tag/0.2.2) to see if you still encounter the same error?

Did not fix the issue.

**Comment by simonSlamka** [comment] 2023-06-13 15:49
> Could you provide a minimal way for me to reproduce this issue?

Unfortunately, I have a lot of extensions and cannot absolutely rule out that one of them isn't causing the issue. However, I just installed your extension, plugged in my API key, opened a random note, where I called the generate input command, after which I called the generate embeddings command, which is where this issue occurred. Pretty much the same response from the API as @lurifaxel had.

**Comment by abimek** [comment] 2023-06-14 04:24
I too had the same issue, I'll try to reproduce this and PR a solution if possible. Still working on the other PR btw!

**Comment by abimek** [comment] 2023-06-18 01:35
I believe it's due to the rate limit, check out https://platform.openai.com/docs/guides/rate-limits/overview.

**Comment by johannesCmayer** [comment] 2023-07-08 11:47
I have the same issue.

**Comment by bbawj** [comment] 2023-08-01 02:33
> I have the same issue, too.
> 
> version 0.3.0 number of batches: 100
> 
> input.csv size nb lines: 10200 nb notes; 143
> 
> embeddings.csv suze nb lines: 205 nb notes processed ; 10
> 
> Console: `Plugin:bbawj-semantic-search:1008 SemanticSearchError(ApiError { message: "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", type: "invalid_request_error", param: None, code: None })`

In this case generate embeddings worked but performing the query does not? Could you post the request payload being sent to the API?

**Comment by bbawj** [comment] 2023-08-01 09:05
> All embeddings are not generated. as you will see in the attached file [obsidian.md-1690879386078_modified.log](https://github.com/bbawj/obsidian-semantic-search/files/12226486/obsidian.md-1690879386078_modified.log) By the way in 'embedding.csv' file the line "name,mtime,header,embedding" is replicated probably for each natch.

Could there be an issue with input row 14 to 21? the first 14 rows seem to be successful.

**Comment by bbawj** [comment] 2023-08-02 08:03
closing this with the release of 0.3.3, please open a new ticket if another issue comes up

**Closed by bbawj** 2023-08-02 08:03 UTC
